services:

  postgres:
    image: postgres:16
    container_name: postgres-db

    restart: always

    env_file:
      - .env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:

    build:
      context: ./backend

    container_name: backend

    restart: always

    env_file:
      - .env

    environment:
      DB_HOST: postgres

    depends_on:
      - postgres

    ports:
      - "8000:8000"

  frontend:

    build:
      context: ./frontend

    container_name: frontend

    depends_on:
      - backend

    ports:
      - "3000:80"

  nginx:

    image: nginx:alpine

    container_name: nginx

    depends_on:
      - frontend
      - backend

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data: